### PR TITLE
Arnold 6.1 support

### PR DESCRIPTION
**Pull request by JenusL**
This update brings support for the following new Arnold features from Arnold 6.1 and 6.0.4.
- Imagers! Use the dummy shader `imager` to connect `imager_*` nodes as Pass and/or Camera LensShaders. Will only use one LensShader slot but you can connect several imagers together. It also properly handles the Pass `OverrideCameraLensShaders` option.
- Dielectric Priorites in `standard_surface` and global render option.
- `add_transparency` added to `mix_shader`
- `rim_light_tint` added to `toon`
- `aov_prefix` added to `toon`
- Default value of `options.texture_max_memory_MB` increased from 2048 to 4096
- Reorganized Sampling tab to better match other Arnold plugins.
- Removed min hard limit on bump_height, making it easy to invert the bump mapping.

Bugfixes:
- Fixed crash with Array Switch shaders #87
- Fixed bug in addon packaging script not creating directories.
- Don't export color_space to deep driver.

Incompatible Changes:
- Hidden lights are no longer exported to Arnold, including to .ass files.

Passes testsuite.

### CODE REVIEW

**Comment by JenusL** [comment]
So I think this is it for SItoA 6.1.0. It might also be the last SItoA i create because second kid will be here any day now and then I'm gonna focus on learning Houdini and more Unreal Engine. But don't worry, I'll continue to use Arnold in Houdini :)
Thanks for all the help @sjannuz and @caron.

**Comment by caron** [comment]
Amazing work Jens! And good luck!

**Comment by JenusL** [comment]
And just like that Arnold 6.2 was release 😂
Will take a look at that and I might make a version for that to.

**Comment by caron** [comment]
Yep, with a cool light mixer imager but that would probably be soo difficult to support in Softimage.

**Comment by JenusL** [comment]
I actually didn't even try sending the "imager render hint" for this release. Might do a quick test just to see if it works. Passing that hint might make Arnold just update the image without re-rendering.

**Comment by JenusL** [comment]
@sjannuz Could we get this merged? I think I'm gonna make one newer version at least... Cant keep my fingers away :)

**Pull request merged**
