### PR TITLE
New Arnold 5.1.0 shaders

### PR DESCRIPTION
**Pull request by JenusL**
Added the following new shaders:
- `layer_float`
- `layer_rgba`
- `layer_shader`
- `toon`

For `toon` to work properly I also added the new `contour` filter. While I was there I noticed that the `sinc` filter was missing so I added that as well.

Two new aovs for the toon shader is also added.

toon is outputting color instead of a closure so it couldn't be added to objects directly with AddShader() so I updated that function to handle non closure shaders as well.

### CODE REVIEW

**Comment by caron** [comment]
i find it curious (i haven't dug in myself just yet) that the toon shader is returning a color and not a closure.

**Comment by JenusL** [comment]
Both the node reference: https://support.solidangle.com/display/A5NodeRef/Toon and `kick -info toon` says output is RGB so nothing wrong there.

**Comment by caron** [comment]
oh, i don't question whether you're right but rather why that is from the dev/core side.

**Comment by JenusL** [comment]
Fixed the conflict.

**Pull request merged**
