### PR TITLE
Add Arnold to PATH

### LINKED ISSUE #8: optix_denoiser.dll not found
SItoA shows the following warning when rendering with Arnold 5.1.0.0

```
// WARNING : [arnold] unable to load dynamic library <local_workgroup_path>\Addons\SItoA\Application\Plugins\bin\nt-x86-64\optix_denoiser.dll: The specified module could not be found.
```
This doesn't make sense because the dll-file is clearly there in the folder with the rest of the core files.
I don't know if it's a problem on Linux as well.
The warning is harmless but annoying for now.
I'm guessing that the Optix Denoiser wouldn't work if it was implemented now.

### PR DESCRIPTION
**Pull request by JenusL**
So to fix the missing optix_denoiser.dll error I added the path to Arnold to PATH environment variable.
It's adding the path on `XSILoadPlugin` and removing it again in `XSIUnloadPlugin`. This way we can reload SItoA as many times as we want without it filling the PATH with paths to Arnold.
I only implemented it for Windows.
This closes #8

### CODE REVIEW

**Comment by caron** [comment]
where any tests created with the annoying ```The specified module could not be found.``` messages? if so, do they need to be updated in this change?

**Comment by JenusL** [comment]
Good question. The last two tests (AOV Shaders and Toon shader) have the warning in their reference logs.
But they still Passes so I wouldn't worry about it.

**Comment by caron** [comment]
gotcha, the images still pass the test... i will pull this into my local branch, compile, and test it on my machine tonight.

**Comment by caron** [comment]
ok, i compiled this and tested. thanks!

**Pull request merged**
