### PR TITLE
Support for Stats and Profiling Diagnostics

### PR DESCRIPTION
**Pull request by JenusL**
This is just initial support for the new Stats and Profiling JSON outputs on the Diagnostics tab.
I would like to have some feedback on what the default filenames of these files should be, because I'm not sure in what context these are supposed to be in. Is it one stats file per frame, per scene, or per pass, etc. The filename will decide how the appending of stats will be.
@sjannuz Any thoughts / recommendations?

**FYI**
Right now the Stats feature seems broken as a simple scene with just a cube is crashing Softimage and kick with Arnold 5.2.1.0. I've reported it to AD and they have created a core ticket.
You can still try out the profile feature with no problem, but if you want to test stats, make sure it's just an empty scene.

I will hold of on this development until a new core version is released that fixes this.

### CODE REVIEW

**Comment by JenusL** [comment]
I talked to support and the bug that crashed Arnold isn't fixed yet in 5.2.2.0 but they told me what was the cause... Stats crashed Arnold if the scene didn't have any subdivision objects. With that info I was able to test this out and finish the development.
Here's the PPG with default paths.
stats_and_profile

**Comment by JenusL** [comment]
Just an FYI.
Arnold core 5.2.2.1 fixes the crash bug
> #7741 Arnold crashes when you try to write out render stats

**Comment by caron** [comment]
Starting to go through these new PRs and wanted to ask about render stats and using 'chrome tracing' tool. Does render stats work with it at all? Loading the json file into 'chrome://tracing/' gives me nothing. Am I using it wrong?

Also, profile doesn't seem to give much information when writing an IPR render out, it works as expected on a full frame render though.

**Comment by JenusL** [comment]
As far as I know it's only the profiling that you can trace in Chrome. The stats is just stats in JSON format.

Yeah, I also noticed that profile didn't work in IPR when I developed. I couldn't find anything in the code to explained that. So I just thought that's how it is then. Maybe it's just because the multiple calls to AiRender() that invalidates the profiling. What happens if you disable all four of the IPR sub-sampling checkboxes?

**Comment by JenusL** [comment]
Ok so I did some tests and it looks like profiling isn't written out until Arnold is closed, and the region is keeping the Arnold universe open of obvious reasons. A Scene Destroy will write out the profile when working with IPR.

**Pull request merged**
