### PR TITLE
Arnold 7.0 support

### LINKED ISSUE #89: Support Arnold 7
Not so much new stuff but quite a few things have changed... especially color managers and denoising.

### PR DESCRIPTION
**Pull request by JenusL**
This update brings support for the following new Arnold features from Arnold 6.2 and 7.0
- OCIO default color manager
- EXR Multipart support
- Denoising imagers:
  - `imager_denoiser_noice` Arnold Denoiser
  - `imager_denoiser_oidn` Intel Open Image Denoise
  - `imager_denoiser_optix` nVidia Optix denoiser
- `imager_lens_effects` now has Bloom
- `imager_tonemap` got support for LUTs + UI enhancements
- `ignore_imagers` render option

Incompatible / Behavior changes
- Default color manager has been changed to use OCIO and default render colorspace has changed to ACEScg.
- GPU settings is now always exported
- `use_existing_tx` is now handled by Arnold core instead of the SItoA plugin

Bugfixes
- Made Arnold handle if shaders are linkable or not. This made some more parameters linkable that was incorrectly set to not be linkable before.

Build system fixes / changes:
- Easy double-click shortcut to open a dev console in cmd or Windows Terminal (if installed)
- Fixed a deadlock bug in testsuite
- Updated all test suite reference images due to the color manager change making them not pass anymore.

Passes testsuite.
This closes #89

### CODE REVIEW

**Comment by JenusL** [comment]
Well there it is. Basic support for Arnold 7. I don't plan to add anything more right now so this can probably be merged now.

**Comment by sjannuz** [comment]
@JenusL I see you updated all the baseline images, were they all different ?

**Comment by JenusL** [comment]
@sjannuz All non-greyscale images were different because of the change in render color space to ACEScg, and the default OCIO color manager made a harder "color grade" on the output images.
I think it was around 40 tests that failed, but the rest had slight color differences in them probably right below the diff threshold. So I thought it was easiest to just update them all.
I carefully went through them to see so nothing else but the colors where different. So all tests passed.

**Review by sjannuz — APPROVED** [review]
Awesome work

**Pull request merged**
