### PR TITLE
Make SItoA compile with Arnold 5.1.0

### PR DESCRIPTION
**Pull request by JenusL**
Just bare minimum changes to make it compile.
We have to look at changing to the new render control API later.
I also bumped SItoA version to 5.0.0-alpha and credited myself :)

### CODE REVIEW

**Comment by caron** [comment]
OK, good to know. i will pull this in if it doesn't get merged by the time i get my hands dirty. i actually thought there would be more changes needed to get it rendering with the new core.

**Comment by JenusL** [comment]
Just ran the testsuite.
2 tests failed: 161(Implementing mesh lights) and 250 (Fixing UVs with boolean operations in Softimage 2013)
Don't know if they failed before my changes because I didn't ran the test before. I'll have to investigate a bit.

**Comment by caron** [comment]
only 2 failures is great news! means for 'testers' they can try it in their pipeline doing batch rendering on the farm.

ya, those seems odd to have failed... i wouldn't spend a buncha time on 250 but the mesh lights one (161) sounds curious.

**Comment by JenusL** [comment]
Just checked the trac and 250 is a Softimage bug that obviously will never get fixed. See 1841 and 1921 on the good old trac for more info. I think I ran into this bug myself in a project and there are workarounds.
Will investigate test 161 now...

**Comment by JenusL** [comment]
Ok I think that the failed mesh light test can be ignored as well.
In Arnold 5.0.1 the mesh_light sampling was improved:

> Improved mesh light sampling: A new sampling algorithm has been implemented for mesh lights which can greatly improve their rendering quality when shading points near the light's surface, particularly in volumes. (#6005, #6062, #6074)

What happens in the test is the mesh itself gets a taste of that improved sampling because it's so close to the light (well the surface IS actually the light).
This fails in SItoA 4.1.0 as well. So it's just a badly designed test and I would probably turn off diffuse on the mesh material so it doesn't happen again... But that's for a later time.
So yeah conclusion is that all 3 pull requests I've added so far doesn't break the test suite at all.

**Comment by caron** [comment]
cool, that all makes sense. nice work

**Comment by sjannuz** [comment]
Correct about the testsuite. The meshlight one should be changed, and the other one was just a special fix for 2013, as the description tells.

**Pull request merged**
